package docsgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// GenerateCLIReference generates a Markdown CLI reference from a root cobra.Command.
func GenerateCLIReference(root *cobra.Command, w io.Writer) error {
	fmt.Fprintf(w, "# %s CLI Reference\n\n", root.Name())
	fmt.Fprintf(w, "> Auto-generated by `%s docs generate`. Do not edit manually.\n\n", root.Name())

	if root.Long != "" {
		fmt.Fprintf(w, "%s\n\n", strings.TrimSpace(root.Long))
	} else if root.Short != "" {
		fmt.Fprintf(w, "%s\n\n", root.Short)
	}

	// Global flags
	if root.PersistentFlags().HasFlags() {
		fmt.Fprintln(w, "## Global Flags\n")
		fmt.Fprintln(w, "| Flag | Type | Default | Description |")
		fmt.Fprintln(w, "|------|------|---------|-------------|")
		root.PersistentFlags().VisitAll(func(f *pflag.Flag) {
			if f.Hidden {
				return
			}
			name := formatFlagName(f)
			fmt.Fprintf(w, "| %s | `%s` | `%s` | %s |\n", name, f.Value.Type(), f.DefValue, f.Usage)
		})
		fmt.Fprintln(w)
	}

	// Commands
	fmt.Fprintln(w, "## Commands\n")
	for _, cmd := range root.Commands() {
		if cmd.Hidden || cmd.Name() == "help" || cmd.Name() == "completion" {
			continue
		}
		writeCommand(w, cmd, 3)
	}

	return nil
}

func writeCommand(w io.Writer, cmd *cobra.Command, headingLevel int) {
	heading := strings.Repeat("#", headingLevel)
	fmt.Fprintf(w, "%s `%s`\n\n", heading, cmd.CommandPath())

	if cmd.Short != "" {
		fmt.Fprintf(w, "%s\n\n", cmd.Short)
	}

	if cmd.Long != "" && cmd.Long != cmd.Short {
		fmt.Fprintf(w, "```\n%s\n```\n\n", strings.TrimSpace(cmd.Long))
	}

	fmt.Fprintf(w, "**Usage:** `%s`\n\n", cmd.UseLine())

	// Local flags
	localFlags := cmd.NonInheritedFlags()
	if localFlags.HasFlags() {
		fmt.Fprintln(w, "| Flag | Type | Default | Description |")
		fmt.Fprintln(w, "|------|------|---------|-------------|")
		localFlags.VisitAll(func(f *pflag.Flag) {
			if f.Hidden {
				return
			}
			name := formatFlagName(f)
			fmt.Fprintf(w, "| %s | `%s` | `%s` | %s |\n", name, f.Value.Type(), f.DefValue, f.Usage)
		})
		fmt.Fprintln(w)
	}

	if cmd.Example != "" {
		fmt.Fprintf(w, "**Examples:**\n\n```\n%s\n```\n\n", strings.TrimSpace(cmd.Example))
	}

	// Subcommands
	for _, sub := range cmd.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		writeCommand(w, sub, headingLevel+1)
	}
}

func formatFlagName(f *pflag.Flag) string {
	if f.Shorthand != "" {
		return fmt.Sprintf("`--%s`, `-%s`", f.Name, f.Shorthand)
	}
	return fmt.Sprintf("`--%s`", f.Name)
}
